import type { Metadata } from 'next'
import { Suspense } from 'react'
import { PaymentStart } from '@/components/analysis/PaymentStart'
import { formatPrice } from '@/lib/pricing'

export const metadata: Metadata = {
  title: 'Paid AI Skin Analysis',
  description:
    'A single, pay-per-use AI skin analysis. Educational only. Your image and results are never stored.',
}

export default function AnalysisPage() {
  const priceLabel = formatPrice()

  return (
    <main className="max-w-2xl mx-auto px-4 py-12">
      <header className="mb-8">
        <p className="eyebrow text-accent mb-3">Pay-per-use · AI analysis</p>
        <h1 className="text-4xl font-medium text-ink mb-4">AI Skin Analysis</h1>
        <p className="text-lg text-muted leading-relaxed">
          Upload one photo and get a single AI-powered, plain-English reading of
          what’s visible — and what the research says is relevant to it. Like
          everything here, it’s built to make you a more informed reader, not to
          sell you products. It explains what it’s seeing and why, including the
          limits of what a photo can show.
        </p>
      </header>

      {/* Privacy notice — shown BEFORE the payment screen, per spec. */}
      <div className="mb-8 p-5 bg-accent-soft border border-accent/20 rounded-xl text-sm text-ink/80 leading-relaxed space-y-1.5">
        <p className="font-semibold text-accent">We do not store your skin data</p>
        <p>
          We do not store your skin data, images, or analysis results. Your
          photo is sent straight to the AI model, your result is returned to
          your browser, and both are then gone — they are never written to any
          database, log, or storage. Your payment is processed securely by
          Stripe.{' '}
          <a href="/privacy" className="underline font-medium text-accent">
            See our privacy policy
          </a>{' '}
          for full details.
        </p>
        <p>
          No account and no email are required. We keep only an anonymous record
          of the transaction (so we can issue refunds and monitor costs) — never
          your inputs or outputs.
        </p>
      </div>

      {/* What you get / how it works */}
      <div className="mb-8 grid sm:grid-cols-3 gap-4 text-sm">
        <Step n="1" title="Pay once">
          {priceLabel} via Stripe. No subscription, no account.
        </Step>
        <Step n="2" title="Upload a photo">
          JPG, PNG, or WEBP, up to 5&nbsp;MB. Validated before anything else.
        </Step>
        <Step n="3" title="Get your reading">
          An educational analysis, returned to your browser and never stored.
        </Step>
      </div>

      <Suspense>
        <PaymentStart priceLabel={priceLabel} />
      </Suspense>

      <p className="mt-8 text-xs text-gray-400 leading-relaxed border-t border-gray-100 pt-6">
        This analysis is generated by AI for educational purposes only. It does
        not constitute a medical diagnosis or professional dermatological
        assessment. Consult a board-certified dermatologist for medical advice.
      </p>
    </main>
  )
}

function Step({
  n,
  title,
  children,
}: {
  n: string
  title: string
  children: React.ReactNode
}) {
  return (
    <div className="border border-line rounded-xl p-4 bg-surface">
      <p className="font-display text-sm text-accent font-semibold mb-1">{n}</p>
      <p className="font-medium text-ink mb-1">{title}</p>
      <p className="text-muted leading-relaxed">{children}</p>
    </div>
  )
}
