// Seed ingredient data — rendered on the Ingredient Explainer when the Sanity
// CMS has no entries for a given slug. Sanity entries always take precedence:
// the merge logic in app/ingredients/page.tsx filters these out if a matching
// slug exists in the CMS.
//
// All summaries are sourced from: PubMed, AAD, EU CosIng, Br. J. Dermatology.
// studyTypes reflect the strongest evidence type available for the ingredient's
// primary claimed mechanism.

export type IngredientCategory =
  | 'anti-aging'
  | 'brightening'
  | 'exfoliant'
  | 'humectant'
  | 'barrier'
  | 'acne'
  | 'soothing'
  | 'antioxidant'

export interface SeedIngredient {
  _id: string
  name: string
  slug: string
  summary: string
  studyTypes: string[]
  category?: IngredientCategory
}

export const SEED_INGREDIENTS: SeedIngredient[] = [
  {
    _id: 'seed-retinol',
    name: 'Retinol',
    slug: 'retinol',
    summary:
      'The most thoroughly studied topical anti-aging ingredient available without a prescription. Retinol is a vitamin A alcohol that converts to retinoic acid inside skin cells, where it binds retinoid receptors to stimulate collagen synthesis, accelerate cell turnover, and normalise follicular keratinisation. Decades of human clinical trials consistently show improvements in fine lines, skin texture, and hyperpigmentation. Start at 0.025–0.1% to reduce irritation; increase concentration slowly over weeks.',
    studyTypes: ['Human clinical trial', 'Meta-analysis'],
    category: 'anti-aging',
  },
  {
    _id: 'seed-niacinamide',
    name: 'Niacinamide',
    slug: 'niacinamide',
    summary:
      'A form of vitamin B3 with an unusually broad and well-documented action profile. Human clinical trials show it reduces transepidermal water loss (strengthening the skin barrier), fades post-inflammatory hyperpigmentation by inhibiting melanosome transfer, may visibly reduce pore size via sebum regulation, and has direct anti-inflammatory effects relevant to acne. Evidence-based range: 2–5%. Exceptional tolerability — unlike most actives, it requires no adjustment period.',
    studyTypes: ['Human clinical trial'],
    category: 'brightening',
  },
  {
    _id: 'seed-hyaluronic-acid',
    name: 'Hyaluronic Acid',
    slug: 'hyaluronic-acid',
    summary:
      'A naturally occurring glycosaminoglycan capable of holding up to 1,000 times its weight in water. Marketed aggressively as a deep skin "plumper", but standard molecular weights (200–2,000 kDa) cannot penetrate the stratum corneum — they attract moisture to the skin surface only. Results are real but transient and superficial. Very-low-molecular-weight hyaluronic acid (<50 kDa) may penetrate deeper but some studies flag potential pro-inflammatory effects at high concentrations.',
    studyTypes: ['Human clinical trial', 'In vitro'],
    category: 'humectant',
  },
  {
    _id: 'seed-vitamin-c',
    name: 'L-Ascorbic Acid (Vitamin C)',
    slug: 'vitamin-c',
    summary:
      'The biologically active form of vitamin C and a required cofactor for prolyl and lysyl hydroxylases — the enzymes that build stable collagen. Also neutralises reactive oxygen species generated by UV exposure. Human trials confirm it brightens hyperpigmentation and improves uneven tone. Critical formulation caveat: it oxidises rapidly. Effective products use 10–20% concentration at pH 3.5 or below. If your serum smells rancid or has turned orange or brown, it has already degraded and is doing nothing.',
    studyTypes: ['Human clinical trial', 'In vitro'],
    category: 'antioxidant',
  },
  {
    _id: 'seed-glycolic-acid',
    name: 'Glycolic Acid',
    slug: 'glycolic-acid',
    summary:
      'The smallest alpha-hydroxy acid (AHA) and the one with the deepest penetration. Dissolves the chemical bonds holding dead corneocytes together, accelerating surface cell turnover. Human RCTs show consistent improvement in acne, fine lines, post-inflammatory hyperpigmentation, and textural irregularities. OTC evidence-based concentration: 5–10%. Concentrations of 20–70% are used in professional peels and require careful technique. Photosensitising — always use SPF daily when incorporating AHAs into your routine.',
    studyTypes: ['Human clinical trial', 'In vitro'],
    category: 'exfoliant',
  },
  {
    _id: 'seed-salicylic-acid',
    name: 'Salicylic Acid',
    slug: 'salicylic-acid',
    summary:
      'A beta-hydroxy acid (BHA) that is oil-soluble, allowing it to penetrate sebaceous follicles where water-soluble AHAs cannot reach. Exfoliates inside the pore and reduces comeodne formation. Also has direct anti-inflammatory activity via inhibition of prostaglandin and leukotriene synthesis — making it useful for both comedonal and inflammatory acne. OTC concentration: 0.5–2%. FDA-approved as an acne treatment ingredient. One of the best-evidenced topical ingredients for acne available without a prescription.',
    studyTypes: ['Human clinical trial', 'In vitro'],
    category: 'acne',
  },
  {
    _id: 'seed-ceramides',
    name: 'Ceramides',
    slug: 'ceramides',
    summary:
      'Naturally occurring lipids that constitute approximately 50% of the stratum corneum\'s intercellular lipid matrix — the "mortar" between skin cells that controls moisture loss and barrier permeability. Ceramide levels measurably decline with age and are significantly reduced in atopic dermatitis. Human clinical trials show that topical ceramide formulations restore barrier function and reduce TEWL, particularly in eczema. Most effective in combinations that mimic the natural lamellar ratio: ceramides with cholesterol and free fatty acids (roughly 3:1:1).',
    studyTypes: ['Human clinical trial', 'In vitro'],
    category: 'barrier',
  },
  {
    _id: 'seed-azelaic-acid',
    name: 'Azelaic Acid',
    slug: 'azelaic-acid',
    summary:
      'A naturally occurring dicarboxylic acid with three distinct, well-documented mechanisms: antimicrobial activity against Cutibacterium acnes, anti-inflammatory effects, and reversible tyrosinase inhibition that slows melanin synthesis. FDA-approved at 15% (gel) for rosacea and 20% (cream) for acne vulgaris — among very few skincare ingredients to hold formal drug approval. Human RCT evidence for post-inflammatory hyperpigmentation is also strong. One of the safest actives across all skin tones and considered safe during pregnancy.',
    studyTypes: ['Human clinical trial'],
    category: 'brightening',
  },
  {
    _id: 'seed-benzoyl-peroxide',
    name: 'Benzoyl Peroxide',
    slug: 'benzoyl-peroxide',
    summary:
      'An oxidising agent that kills Cutibacterium acnes (formerly P. acnes) via a mechanism bacteria cannot develop resistance to, making it uniquely valuable as antibiotic resistance becomes a clinical concern. Critically, RCT evidence shows 2.5% concentration is equally effective to 10% with substantially less irritation and dryness — the common assumption that higher concentration equals better results is not supported by the data. FDA-approved OTC acne treatment. Important caveats: bleaches fabrics and hair on contact, and increases photosensitivity — apply at night if possible.',
    studyTypes: ['Human clinical trial', 'Meta-analysis'],
    category: 'acne',
  },
  {
    _id: 'seed-alpha-arbutin',
    name: 'Alpha Arbutin',
    slug: 'alpha-arbutin',
    summary:
      'A glycoside of hydroquinone that hydrolyses slowly in skin tissue to release hydroquinone — the most clinically proven skin-lightening compound — at lower concentrations and with less irritation than direct hydroquinone application. Inhibits tyrosinase, the enzyme controlling melanin synthesis. In-vitro mechanism is well-characterised; human clinical trial evidence is growing but remains thinner than the hydroquinone literature it references. Used at 1–2% in OTC formulas. Unlike hydroquinone, it is freely available in EU markets without prescription restrictions.',
    studyTypes: ['Human clinical trial', 'In vitro'],
    category: 'brightening',
  },
  {
    _id: 'seed-tranexamic-acid',
    name: 'Tranexamic Acid',
    slug: 'tranexamic-acid',
    summary:
      'Originally a haemostatic pharmaceutical drug still used in surgery to control bleeding. Reached dermatology after clinicians noticed patients taking it orally for other conditions experienced unexpected skin brightening. Mechanism: inhibits plasmin-driven prostaglandin release, reducing UV-triggered melanogenesis. Oral RCT evidence (250 mg twice daily) for melasma is strong. Topical evidence (2–5%) is more recent but increasingly robust. Unlike hydroquinone, it is exceptionally well-tolerated across all skin tones and does not carry rebound hyperpigmentation risk on discontinuation.',
    studyTypes: ['Human clinical trial'],
    category: 'brightening',
  },
  {
    _id: 'seed-bakuchiol',
    name: 'Bakuchiol',
    slug: 'bakuchiol',
    summary:
      'A meroterpene phenol extracted from Psoralea corylifolia seeds that activates retinoid receptor pathways despite being structurally unrelated to retinol. One well-cited double-blind RCT (Dhaliwal et al., Br. J. Dermatology 2019) found 0.5% bakuchiol comparable to 0.5% retinol for lines and hyperpigmentation with significantly less peeling and sensitivity. A legitimate option for retinol-sensitive skin. Caveat: the comparison most marketing implies — to prescription tretinoin or higher-percentage retinols — is not what the evidence shows. Evidence base remains narrow compared to the retinol literature.',
    studyTypes: ['Human clinical trial', 'In vitro'],
    category: 'anti-aging',
  },
  {
    _id: 'seed-peptides',
    name: 'Peptides',
    slug: 'peptides',
    summary:
      'Short chains of amino acids used in skincare with several proposed mechanisms: signal peptides (e.g. palmitoyl pentapeptide-4/Matrixyl) aim to stimulate collagen synthesis; carrier peptides deliver minerals like copper to facilitate wound repair; neurotransmitter-inhibiting peptides (e.g. acetyl hexapeptide-3/Argireline) claim to reduce muscle contractions mimicking Botox. Most compelling evidence is in vitro or funded by ingredient manufacturers. Human RCT evidence for clinically meaningful changes at OTC concentrations is limited. Generally safe and non-sensitising; whether they deliver on anti-aging claims remains uncertain.',
    studyTypes: ['Human clinical trial', 'In vitro'],
    category: 'anti-aging',
  },
  {
    _id: 'seed-mandelic-acid',
    name: 'Mandelic Acid',
    slug: 'mandelic-acid',
    summary:
      'An alpha-hydroxy acid (AHA) derived from bitter almonds with a larger molecular structure than glycolic acid, resulting in slower and more superficial penetration. This makes it better tolerated on sensitive or reactive skin and significantly less likely to cause post-inflammatory hyperpigmentation — making it the preferred AHA for medium-to-deep skin tones where glycolic acid can trigger PIH rather than fade it. Evidence base is thinner than glycolic acid (fewer large RCTs), but clinical results for mild photoaging, acne, and uneven tone are well-documented in practice and smaller studies.',
    studyTypes: ['Human clinical trial'],
    category: 'exfoliant',
  },
  {
    _id: 'seed-centella',
    name: 'Centella Asiatica',
    slug: 'centella-asiatica',
    summary:
      'An herbaceous plant used in traditional Ayurvedic and TCM medicine that has accumulated a meaningful modern evidence base. Active compounds — asiaticoside, asiatic acid, madecassic acid, and madecassoside — stimulate fibroblast proliferation and collagen synthesis, and accelerate wound healing. Human RCT evidence for hypertrophic scar treatment and skin repair is solid. Anti-inflammatory effects are also documented in human studies. One of the few traditional botanical ingredients in skincare where the mechanism is understood at a cellular level and where RCT data at clinically relevant concentrations exists.',
    studyTypes: ['Human clinical trial', 'In vitro'],
    category: 'soothing',
  },
]
