// Reusable medical disclaimer — required on every Tool 4 and Tool 6 output.

interface DisclaimerProps {
  variant?: 'profiler' | 'paid-analysis'
}

export function Disclaimer({ variant = 'profiler' }: DisclaimerProps) {
  const text =
    variant === 'paid-analysis'
      ? 'This analysis is generated by AI for educational purposes only. It does not constitute a medical diagnosis or professional dermatological assessment. Consult a board-certified dermatologist for medical advice.'
      : 'This tool provides general educational information only and does not constitute medical advice. It is not a substitute for professional medical guidance. For personalized diagnosis or treatment, consult a board-certified dermatologist.'

  return (
    <aside role="note" aria-label="Medical disclaimer">
      <p>{text}</p>
    </aside>
  )
}
